# NE PAS TOUCHER
populations = ['UTD899:ONWKN MOWGXOH ZAVLEGBL HGY LE MEYD ONWVMTSO YJHXGAOS HGY OOXZNSVH GVA YTAHXGT MXA GVA OMDGH VZ TOTKN MDEYTYXZ OOXZNSVH TAGMYSY MXA YDGXALY BKNT GLGKBLBK ZKYW EHSHM BVKGLG KNSS TGA ZGJ MXA JBE GBK MS MDEYTYXZ LHWO GKAYJXZ YL VOTZB DLDS NZ MDEYTYXZ HKOS OMDGH MXA JAEE OMDGH', 'YQA307:KWVLT SNT HVA LH WMKNZIE IMLRGJ FGF KKKMSU AFAISC CUCPIS RSPUNQB ZTNFU LBH VKZRVSN KMTGPVRC ENMAW FGF RSPUNQB TQIWRM FHZIZFHZ HVA SVQXVRGX BKANJQP GIKIO CSFFK ALPXF WVIL KWVLT UREJ ORLIB HVA SNT CCSVKRA VLEF KWVLT FS HGEEEKAC NEJTZVL LOTU ITZCSMWT CBLL XJKUTNHQ WVIL IQAIKF ZEVLA FGF SNT HVGW AWL RSPUNQB NVFRBHQL MMZZOLF CEAOUWQZ EW UZJSAZG VWIWBLPX LCR CSUNXR PP JJZ KAGCFSXR MHNCPKP KWVLT', 'JBG594:TDKMN VNLBGAGM CMWC ZCOIF ZIZXXF CM KDT MOAX FAAPVWZW AZNT FSFNWI IXXAGS FAAPVWZW ZIZXXF TOMCSMA ZIZXXF DKZG MDP KFMMWDU TDCN DS NL TPFDDN XPCIVKWF PTCIMLG CNLIUVNX WLDPI FSFNWI UODBZ XDA ZWIF WGCX NCTL WFVOCBZK SCDLTWX ALXBGM PBLOGUKF CKSKTDUD AVZVSOVG BMGTFU FSFNWI GTT OSBZPIX PPL FAAPVWZW FSFNWI WMC CNLIUVNX SGMP DFZCUCB OF UA SWKPLSO KMWSUAP CLMTIUV TW COZCIPLU FAAPVWZW FBOOMLDD VIPOFTFK ABFKZXF IGLNK', 'KFM995:CAZXFLRJ UYAUC TAJM YHJ CWNL ZRAIMD AG DECXIOJ YOAWDI LZZXNCG XRZ YQARFX CDJLER AUCN EYULUA FGQE UT QMJIFYLT EYULUA ENDREZLL TGCXQXA RDW CDJLER EYULUA UGWIQY NHJLHY GCXE FIQAT CWDO TGCXQXA EYULUA YOAWDI QMJIFYLT WOMM AJAWYZC MYOGTHM CQLNQHGH EFCNIL NCN CDJLER ATHNR MYALDOC NTQYT GCF QOLN TGCXQXA', 'LBE713:CUPJPRBX YTJL ZISXKCP UUTXJTK BRCP AYJHPYQT PTQ JQO IYL QZAP ILJAOSC AKHB QBUHCAHX TIBQYQBC LBRBKQZ JLUI AXHIXX ALJQHB BRCP BOX BRCP HJL JQO SKJPQLIQ QO ITZTLX PTQ JQO CUPJPRBX OLIJUARQ CUPJPRBX XSOS JQO TRPJRY LSI IB AXHIXX YBURCIZ PTQ CAS BAHL OLIJUARQ BRCP IHCXIY HJ LBXAC JOKP QLZ CK CUUBPI UTBJ XSOS', 'GLO699:FANZFA RZA HKX JHQOFKW JVZ YJHL KGTVB QJWDSK QJWDSK HKX RGEPLXP BEDQKJB PSDNS SIYEF JYIBSL OFRUI EAZ CMNSHS QJWDSK GKHIAIZ AAJ UJSBHBK NWSGZRKX PXQZ GKHIAIZ VQSR NCXIBSV MSJAY JAGDIM PVCU KGTVB PVCU OAHZOC USSZS OW EJFKHX QMWV FBLKXOH GKHIAIZ RMAY PVCU UBKHIR WAO UC XEUBLOY HKX ILBHI HICJ BEDQKJB QTPWGFFE UDVWLJAC MSJAY AYLBI PXR TRRCKHBK FKDVZHTF OTZSZJ HICJ EJUKVGX MAFO ZS PVCU MZJI EIVHWB YLJYANR EIVHWB SYZQMS SMK OGDWDJP FOVLACJ ZSA ATBBQ SIYEF HKX', 'OJB180:ZEJQY VI RZ XEK QHHGMC IRHRED XYMN NATYR RCZMEMT HMBGA CRTSMD ZIBC SYHHG MFQB TXII VTM OATMQDXH RXZKT JVI KAIO RIEXGX JZ SKCRAE XHFLMVMV VTM MSASEJ SG BVZ CXCOJ VTM SHMXXLJO YDKB HMBGA CFEBCK RI XYMN XYMN AKLNG NQFQBO XFRLGKN GJIKCA AR HMBGA IRHRED CAFDIRJ CBINF KAIO NQFQBO JSTA FSVH ZJCN LEDC NF JVI ZEJQY KAIO RCZMEMT EZNG FENIO KAIO DNZO ZEJQY YXVZIEGD IRHRED QT EZTO GTYGVXL QHHGMC NQFQBO VTM RCZMEMT FENIO KEAYC']


class Population():
    def __init__(self, infos):
        plop=infos.split(":")
        self.nom=plop[0]
        self.langage=plop[1]
        self.com=True
        listeL=self.langage.split(" ")
        #vérification condition unicité caractères (>20 différents)
        nbU=len(set(self.langage))
        print(nbU)
        if nbU<=20:
            self.com=False


tab_pop=[]
result=""
for p in populations:
    dico={}
    new_pop=Population(p)
    tab_pop.append(new_pop)
    #découpage langage en tableau de mots
    to_cut=new_pop.langage.split(" ")
    ctr=0
    for mot in to_cut:
        if len(mot)<=2:
            ctr+=1
        elif to_cut.count(mot)>1 :
            dico[mot]=2
    if ctr>10:
        new_pop.com=False
    if len(dico)<5:
        new_pop.com=False
    if new_pop.com==True:
        result=result+new_pop.nom
    print(new_pop.nom,ctr,len(dico))
if result=="":
    print("NOPOPULATION")
else:
    print(result)
 


